In [1]:
import numpy as np


In [2]:
arr=np.random.randn(4,4)

In [3]:
arr

array([[ 1.61667871, -0.44250272,  1.94376247, -1.15900537],
       [ 0.39968317,  0.59710801,  1.07947682, -0.41817215],
       [-0.51191078, -0.7541928 ,  0.73489641, -0.66412056],
       [ 0.03536487, -1.29464956,  0.5353534 ,  2.26812123]])

In [4]:
arr.sum()

3.9658911631835334

In [5]:
arr.mean()

0.24786819769897084

In [6]:
arr.var()

1.1077939261268446

In [7]:
arr.std()

1.052517898245367

In [8]:
np.where(arr<0)


(array([0, 0, 1, 2, 2, 2, 3], dtype=int64),
 array([1, 3, 3, 0, 1, 3, 1], dtype=int64))

In [9]:
np.where(arr<0,0,arr)

array([[1.61667871, 0.        , 1.94376247, 0.        ],
       [0.39968317, 0.59710801, 1.07947682, 0.        ],
       [0.        , 0.        , 0.73489641, 0.        ],
       [0.03536487, 0.        , 0.5353534 , 2.26812123]])

In [10]:
arr.sort()

In [11]:
arr

array([[-1.15900537, -0.44250272,  1.61667871,  1.94376247],
       [-0.41817215,  0.39968317,  0.59710801,  1.07947682],
       [-0.7541928 , -0.66412056, -0.51191078,  0.73489641],
       [-1.29464956,  0.03536487,  0.5353534 ,  2.26812123]])