In [1]:
import numpy as np


In [2]:
b=np.random.random((3,3))

In [3]:
c=np.random.random((3,3))

In [4]:
b

array([[0.69829407, 0.15568564, 0.39159326],
       [0.2577049 , 0.89838961, 0.56407425],
       [0.19142558, 0.10212813, 0.53427677]])

In [5]:
c

array([[0.07621099, 0.41323703, 0.47016828],
       [0.51593255, 0.60588136, 0.66986029],
       [0.68995917, 0.51309455, 0.0170613 ]])

In [6]:
b + c

array([[0.77450506, 0.56892267, 0.86176154],
       [0.77363745, 1.50427097, 1.23393454],
       [0.88138475, 0.61522268, 0.55133807]])

In [7]:
b -c

array([[ 0.62208308, -0.25755139, -0.07857501],
       [-0.25822765,  0.29250825, -0.10578604],
       [-0.49853359, -0.41096642,  0.51721547]])

In [8]:
b*c

array([[0.05321768, 0.06433507, 0.18411473],
       [0.13295835, 0.54431752, 0.37785094],
       [0.13207584, 0.05240139, 0.00911546]])

In [9]:
b/c

array([[ 9.16264261,  0.37674659,  0.83287896],
       [ 0.49949339,  1.4827814 ,  0.84207746],
       [ 0.2774448 ,  0.19904349, 31.31512607]])

In [10]:
b%c

array([[0.01239515, 0.15568564, 0.39159326],
       [0.2577049 , 0.29250825, 0.56407425],
       [0.19142558, 0.10212813, 0.00537646]])

In [11]:
1/c

array([[13.12146696,  2.41991868,  2.12689807],
       [ 1.93823784,  1.65048815,  1.49284861],
       [ 1.44936112,  1.94895853, 58.61218021]])

In [12]:
2/b

array([[ 2.86412283, 12.84639993,  5.10734015],
       [ 7.76081478,  2.22620562,  3.5456325 ],
       [10.44792432, 19.58324327,  3.7433782 ]])

In [13]:
b += c #b=b+c

In [14]:
b

array([[0.77450506, 0.56892267, 0.86176154],
       [0.77363745, 1.50427097, 1.23393454],
       [0.88138475, 0.61522268, 0.55133807]])

In [15]:
 b**2

array([[0.59985809, 0.323673  , 0.74263295],
       [0.59851491, 2.26283115, 1.52259445],
       [0.77683908, 0.37849894, 0.30397366]])

In [16]:
0.52522541 *0.52522541

0.2758617313096681

In [17]:
1.45346678 * 1.45346678

2.1125656805635686